spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myslot
    username: postgres
    password: muffin@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true